server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /test
    session:
      cookie:
        name: SESSION
        path: /api/
        http-only: false
        timeout: 1800
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://192.168.252.212:3307/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    maxActive: 400
    initialSize: 5
    maxWait: 60000
    minIdle: 100
redis:
  single:
    host: 10.10.220.201
    port: 6379
  cluster:
  #    nodes: 192.168.252.211:7000,192.168.252.212:7000,192.168.252.213:7000,192.168.252.211:7001,192.168.252.212:7001,192.168.252.213:7001,192.168.252.211:7002,192.168.252.212:7002,192.168.252.213:7002,192.168.252.211:7003,192.168.252.212:7003,192.168.252.213:7003
  #    maxRedirects: 6
  common:
    password: redis
    dbIndex: 0
    maxActive: 20  # 连接池最大连接数（使用负值表示没有限制，对应maxTotal）
    max-idle: 20   # 连接池中的最大空闲连接
    min-idle: 1    # 连接池中的最小空闲连接
    maxWait: -1    #等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
    testOnBorrow: true #在borrow一个jedis实例时，是否提前进行validate操作；如果为true，则得到的jedis实例均是可用的
    testOnReturn: false #jedis调用returnObject方法时，是否进行有效检查
    timeout: 100000

